### ISSUE TITLE
Make axes dep optionnal

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/django_ynh#11]
Thanks for building this app :-).

Axes is not strictly required for a django-ynh app.

IMHO using it or not should be made a decision of dev/pkger but not forced by django_ynh.

Could it be made optionnal (like, try to import axes, if failed use regular django exceptions instead of axis specific ones) ?

**Comment by jedie** [comment]
Hm. Django-Axes is used to "log" logins and if something wong by raise `AxesBackendPermissionDenied` in moddleware.

See: https://github.com/YunoHost-Apps/django_ynh/blob/testing/django_ynh/sso_auth/auth_middleware.py

Yes, this is not really needed.

The idea was to create fail2ban entries. But don't know how, see: https://forum.yunohost.org/t/django-app-fail2ban/13751

Maybe we can only send failed logs to fail2ban and remove axes?

**Comment by JocelynDelalande** [comment]
I think this is not necessary, I explain my point :

we rely on django SSO for authentication, so failed login attempts will be caught already by yunohost sso.

Or is it something else than failed login attempts that you try to catch ?

WDYT ?

**Comment by jedie** [comment]
I tried to catch miss-configurations and SSO API changes by assert the whole header stuff. Fail fast ;)

I change `django_ynh/sso_auth/auth_middleware.py` to work without Django-Axes.

**Comment by jedie** [comment]
deps removed, so i close this issues.
