### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/django_ynh#12]
Dependencies, according to *pyproject.toml* are :

```
gunicorn = "*"
django-axes = "*"  # https://github.com/jazzband/django-axes
psycopg2-binary = "*"
django-redis = "*"
```

I do not realy see why they are systematically required for any django project packaged for ynh (see #11 for axes-specific discussion).

Any elements on why they are here and should remain ?

Thanks by advance :-).

**Comment by jedie** [comment]
Hm... Yes the only real sepency is django-axes... I will remove the others...

**Comment by jedie** [comment]
@JocelynDelalande Can you review https://github.com/YunoHost-Apps/django_ynh/pull/14/files please?

**Comment by JocelynDelalande** [comment]
Yes, this is ongoing :-).

**Comment by jedie** [comment]
deps removed, so i close this issues.
